# This file lists tools managed by Aftman, a cross-platform toolchain manager.
# For more information, see https://github.com/LPGhatguy/aftman

# To add a new tool, add an entry to this table.
[tools]
lune = "lune-org/lune@0.8.4"
selene = "kampfkarren/selene@0.27.1"
stylua = "johnnymorganz/stylua@0.20.0"
wally = "UpliftGames/wally@0.3.2"
# rojo = "rojo-rbx/rojo@6.2.0"